CREATE TABLE IF NOT EXISTS accounts(id TEXT PRIMARY KEY,client TEXT,platform TEXT,handle TEXT,ext_id TEXT DEFAULT '',pe INTEGER DEFAULT 2,sg INTEGER DEFAULT 1,dm INTEGER DEFAULT 0,cm INTEGER DEFAULT 0,ad INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS days(acc TEXT,day TEXT,p INTEGER DEFAULT 0,s INTEGER DEFAULT 0,lp INTEGER DEFAULT 0,PRIMARY KEY(acc,day));
